Insightish/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('titanic.urls')),
    path('admin/', admin.site.urls),
]

titanic/urls.py
from django.urls import path
from titanic import views
app_name = 'titanic'

urlpatterns = [
    path('', views.titanic_home, name='titanic_home'),
    path('predict/', views.titanic_get_result, name='titanic_result')
]

home/models.py
from django.db import models

# Create your models here.

titanic/models.py
from django.db import models


# Create your models here.


class Passenger(models.Model):
    age = models.IntegerField()
    siblings_and_spouse_count = models.IntegerField()
    parent_and_children_count = models.IntegerField()
    gender = models.CharField(max_length=6)
    ticket_number = models.CharField(max_length=100)
    passenger_class = models.CharField(max_length=10)
    cabin_number = models.CharField(max_length=20)
    fare = models.IntegerField()
    port_of_embarkation = models.CharField(max_length=20)
    name = models.CharField(max_length=200, default='')

    def __str__(self):
        return self.name + ' - ' + str(self.age) + ' - ' + self.gender


class Predictions(models.Model):
    passenger = models.ForeignKey(Passenger, on_delete=models.CASCADE)
    survival_prediction = models.IntegerField(default=1)
    prediction_confidence = models.IntegerField()

    def __str__(self):
        return str(self.passenger) + ' - ' + str(self.survival_prediction) + ' - ' + str(self.prediction_confidence)

home/views.py
from django.shortcuts import render

# Create your views here.

titanic/views.py
import pandas as pd
from django.shortcuts import render
from titanic import services
# Create your views here.


def titanic_home(request):
    return render(request, 'titanic/titanic_main.html')


def titanic_get_result(request):
    try:
        temp_dict = request.POST.dict()
        output_tray = {1: 'Surviving', 0: 'Not Surviving'}
        data = pd.DataFrame(temp_dict, index=[0])
        prediction, confidence = services.predict(data)

    except Exception as e:
        raise e
    return render(request, 'titanic/titanic_result.html',
                  {'prediction': output_tray[prediction],
                   'prediction_confidence': round(max(confidence[0])*100, 2)})

titanic/templates/titanic/titanic_main.html
{% load static %}

<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'titanic/titanic_main.css' %}"/>
    <title>Titanic Survival Prediction</title>

</head>
<body>
<div class="main-container">
    <div class="wrapper">

        <h1 class='main-heading'>Titanic Survival Prediction</h1>

        <div class="main-panel">
            <form action="{% url 'titanic:titanic_result' %}" method="post">
                {% csrf_token %}
                <fieldset>
                    <legend>Personal Information</legend>

                    <label for="Name"><span>Name </span><input type="text" class="input-field"
                                                               name="Name"/></label>
                    <br>
                    <label for="Age"><span>Age </span><input type="text" class="input-field"
                                                             name="Age"/></label>
                    <br>
                    <label for="SibSp"><span>Siblings & Spouse Count </span><input type="text"
                                                                                   class="input-field"
                                                                                   name="SibSp"/></label>
                    <br>
                    <label for="Parch"><span>Parent & Children Count</span> <input type="text"
                                                                                   class="input-field"
                                                                                   name="Parch"/></label>
                    <br>


                    <label for="Sex">
                        <span>Gender</span>
                        <select name="Sex">
                            <option value="male">Male</option>
                            <option value="female">Female</option>
                        </select>
                    </label>

                </fieldset>

                <fieldset>
                    <legend>Travel Information</legend>
                    <label for="Ticket"><span>Ticket Number</span><input type="text"
                                                                         name="Ticket"/></label>
                    <br>
                    <label for="Pclass"><span>Passenger Class</span>
                        <select name="Pclass">
                            <option value="1">First</option>
                            <option value="2">Second</option>
                            <option value="3">Third</option>
                        </select>
                    </label>
                    <br>
                    <label for="Cabin"><span>Cabin Number </span><input type="text"
                                                                        name="Cabin"/></label>
                    <br>
                    <label for="Fare"><span>Fare </span><input type="text" name="Fare"/></label>
                    <br>
                    <label for="Embarked"><span>Port of Embarkation</span>
                        <select name="Embarked">
                            <option value="C">Cherbourg</option>
                            <option value="Q">Queenstown</option>
                            <option value="S">Southampton</option>
                        </select>
                    </label>
                </fieldset>

                <input type="submit" value="Predict"/>


            </form>
        </div>
    </div>
</div>

</body>
</html>

titanic/templates/titanic/titanic_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Prediction</title>
</head>
<body>
    <h1>{{ prediction_confidence }}% sure about {{ prediction }}</h1>

</body>
</html>